name: Auto Train Snake

on:
  workflow_dispatch:  # Trigger manually from GitHub → Actions tab

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repo
      uses: actions/checkout@v3

    - name: 🧰 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: 📦 Install dependencies
      run: npm install

    - name: 🧠 Train the snake
      run: npm run train

    - name: 💾 Commit trained config_best.json
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add config_best.json training_log.csv
        git commit -m "🤖 Auto-trained new config" || echo "No changes to commit"
        git push
